-- MySQL Script generated by MySQL Workbench
-- Sat Aug 10 00:06:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chat_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chat_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chat_schema` DEFAULT CHARACTER SET utf8 ;
USE `chat_schema` ;

-- -----------------------------------------------------
-- Table `chat_schema`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat_schema`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `ddd` VARCHAR(2) NOT NULL,
  `country_code` VARCHAR(2) NOT NULL, 
  `phone_number` VARCHAR(9) NOT NULL, 
  `created_at` DATE NOT NULL,
  `updated_at` DATE NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `userId_UNIQUE` (`user_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat_schema`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat_schema`.`contacts` (
  `contact_id` INT NOT NULL AUTO_INCREMENT,
  `user_owner_id` INT NOT NULL,
  `user_referenced_id` INT NOT NULL,
  `created_at` DATE NOT NULL,
  `updated_at` DATE NULL,
  `nickname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`contact_id`),
  UNIQUE INDEX `userId_UNIQUE` (`contact_id` ASC) ,
  INDEX `fk_user_owner_idx` (`user_owner_id` ASC) ,
  INDEX `fk_user_referenced_idx` (`user_referenced_id` ASC) ,
  CONSTRAINT `fk_user_owner`
    FOREIGN KEY (`user_owner_id`)
    REFERENCES `chat_schema`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_referenced`
    FOREIGN KEY (`user_referenced_id`)
    REFERENCES `chat_schema`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  UNIQUE `fk_unique_owner_referenced`(`contacts`, `user_owner_id`, `user_referenced_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat_schema`.`chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat_schema`.`chats` (
  `chat_id` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT(500) NOT NULL,
  `contact_id` INT NOT NULL,
  `created_at` DATE NOT NULL,
  `updated_at` DATE NULL,
  `recived_at` DATE NOT NULL,
  PRIMARY KEY (`chat_id`),
  UNIQUE INDEX `userId_UNIQUE` (`chat_id` ASC) ,
  INDEX `fk_contact_id_idx` (`contact_id` ASC) ,
  CONSTRAINT `fk_contact_id`
    FOREIGN KEY (`contact_id`)
    REFERENCES `chat_schema`.`contacts` (`contact_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
